DELETE http://localhost:3001/api/blogs/6708a650e32da22daddacc96
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzA4NmY0MjJkOGUzMWRmZTY0YTZiMWEiLCJpYXQiOjE3Mjg2MTUzMDYsImV4cCI6MTcyODYxODkwNn0.x76GmT7t19oo-s4RKsFS9j6ZZ1-NuP47Mu-xNhbZ_ac